apiVersion: "v1"
kind: "Secret"
metadata:
  name: "my-database-secret"
  annotations:
    description: "Replace these values with your actual database credentials"
stringData:
  user: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
